### ISSUE TITLE
I want my app to use only Speakerphone, Wired headset, and Bluetooth as Audio Device. When wired headset or bluetooth is disconnected, it selects Earpiece instead of speakerphone.

### ISSUE THREAD

**Issue by aparajita-sinha** [twilio/audioswitch#45] opened 2020-07-30 15:28 UTC
**Describe the bug**
For my app, if a wired headset or Bluetooth is not connected, it should route audio through the speakerphone. I have selected speakerphone as the default audio device but when I disconnect the wired headset or Bluetooth, it goes back to the earpiece.

**To Reproduce**
1. Launch the video app.
2. The speakerphone will be selected by default. (Code snippet added below)
3. Now connect to a wired headset. The audio will be routed through a wired headset.
4. Now disconnect the wired headset.
5. Audio from remote participant can be heard from earpiece instead of speakerphone.

**Expected behavior**
When wired headset or Bluetooth is disconnected it should route audio through the speakerphone.

**Actual behavior**
After a wired headset or Bluetooth is disconnected, it routes audio through the earpiece.

**Android Device**
 - Device: Moto Z2 Play
 - API Version: 29

**Version**
- Version: 0.2.0

```
protected void onCreate(Bundle savedInstanceState) {
        savedVolumeControlStream = getVolumeControlStream();
        setVolumeControlStream(AudioManager.STREAM_VOICE_CALL);

       audioDeviceSelector.start((audioDevices, audioDevice) -> {
            Toast.makeText(this, audioDevice.getName(), Toast.LENGTH_SHORT).show();
            return Unit.INSTANCE;
        });

        List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
        AudioDevice.Speakerphone speakerphone = null;

        for (AudioDevice audioDevice : availableAudioDevices) {
            Log.d(TAG, "Available Audio devices - " + audioDevice.getName());
            if(audioDevice instanceof AudioDevice.Speakerphone) speakerphone = (AudioDevice.Speakerphone) audioDevice;
        }
        audioDeviceSelector.selectDevice(speakerphone);
        audioDeviceSelector.activate();
}
```

**Comment by Alton09** [comment] 2020-07-30 16:24
Hi @aparajita-sinha ! Thanks for submitting this issue. Is your app invoking `activate()` after every time `selectDevice(speakerphone)` is called? `activate()` is only meant to be called one time when your app is ready to route audio to the selected device. It wasn't designed to be invoked multiple times, although you may have found a corner case here that we need to test.

**Comment by aparajita-sinha** [comment] 2020-07-30 17:06
Hi @Alton09, 
No the activate() is not called everytime. It is only for the first time.
Even if I try to get the instance of the AudioDevice in the audioDeviceSelector.start() method and activate the speakerphone forcefully the app starts behaving abnormally. It constantly calls the getAvailableAudioDevices() and falls in a loop and the app crashes.

**Comment by Alton09** [comment] 2020-07-30 17:34
Thanks for that info @aparajita-sinha . I've created [a branch](https://github.com/twilio/twilio-video-app-android/commit/8b7276461841d0a8b72fcbedf671f70cc66f1670#diff-44b417d93e1e540b3a4c5696d117dc34R313) in the Twilio Video App repository with the code snippet you provided above, and I was not able to reproduce the bug. Is there anything missing that your app does differently here? Also, if you could provide the logcat logs when running into this issue it would help us troubleshoot further. Thanks!

**Comment by aparajita-sinha** [comment] 2020-07-30 18:03
Hi @Alton09, I am adding the code snippet here. Also, I have added these lines in the Twilio Video Quickstart app.

```
    private AudioDeviceSelector audioDeviceSelector;
    private int savedVolumeControlStream;
```

   ```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

        audioDeviceSelector = new AudioDeviceSelector(getApplicationContext());
        savedVolumeControlStream = getVolumeControlStream();
        setVolumeControlStream(AudioManager.STREAM_VOICE_CALL);

        /*
         * Start the audio device selector after the menu is created and update the icon when the
         * selected audio device changes.
         */
        audioDeviceSelector.start((audioDevices, audioDevice) -> {
            Toast.makeText(this,audioDevice.getName(),Toast.LENGTH_SHORT).show();
            return Unit.INSTANCE;
        });

List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
        Speakerphone speakerphone = null;
        for (AudioDevice audioDevice : availableAudioDevices) {
            Log.d(TAG, "Available Audio devices - " + audioDevice.getName());
            if(audioDevice instanceof Speakerphone) {
                speakerphone = (Speakerphone) audioDevice;
            }
        }

        audioDeviceSelector.selectDevice(speakerphone);
        audioDeviceSelector.activate();
}

```
```
   @Override
    protected void onDestroy() {
        /*
         * Tear down audio management and restore previous volume stream
         */
        audioDeviceSelector.stop();
        setVolumeControlStream(savedVolumeControlStream);
}

```
```
           @Override
            public void onConnectFailure(Room room, TwilioException e) {
                Toast.makeText(VideoActivity.this,"onConnectFailure - "+e.getMessage(), Toast.LENGTH_SHORT).show();
                audioDeviceSelector.deactivate();
                intializeUI();
            }

```
```
          @Override
            public void onDisconnected(Room room, TwilioException e) {
                Toast.makeText(VideoActivity.this,"onDisconnected", Toast.LENGTH_SHORT).show();
                localParticipant = null;
                reconnectingProgressBar.setVisibility(View.GONE);
                VideoActivity.this.room = null;
                // Only reinitialize the UI if disconnect was not called from onDestroy()
                if (!disconnectedFromOnDestroy) {
                    audioDeviceSelector.deactivate();
                    intializeUI();
                    moveLocalVideoToPrimaryView();
                }
            }

```

**Comment by Alton09** [comment] 2020-07-30 20:26
Thanks @aparajita-sinha . Can you please share a stack trace or some of the error logs that you are seeing in logcat? Also, are you seeing this crash in the video quickstart as well? Or is it just in your app?

**Comment by aparajita-sinha** [comment] 2020-08-03 08:09
Hi @Alton09, 
Using the above code, if I connect to Bluetooth first and then connect to the room, it still connects as a speakerphone. I need to manually select Bluetooth.
After I disconnect the Bluetooth by clicking on my phone's Bluetooth option, it goes back to the earpiece. 
This is applicable to my app as well as the quickstart app.

This below log is from `'audioSwitch' : '0.1.3'`. The app becomes unresponsive.

**Code snippet**
```
private void updateAudioDevice(AudioDevice selectedAudioDevice) {
        audioDeviceSelector.selectDevice(selectedAudioDevice);
    }
```

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video);

        audioDeviceSelector = new AudioDeviceSelector(getApplicationContext());
        savedVolumeControlStream = getVolumeControlStream();
        setVolumeControlStream(AudioManager.STREAM_VOICE_CALL);

        audioDeviceSelector.start((audioDevices, audioDevice) ->{
            updateAudioDeviceIcon(audioDevice);
            return Unit.INSTANCE;
        });

        List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
        Speakerphone speakerphone = null;
        for (AudioDevice audioDevice : availableAudioDevices) {
            Log.d(TAG, "Available Audio devices - " + audioDevice.getName());
            if(audioDevice instanceof Speakerphone) speakerphone = (Speakerphone) audioDevice;
        }
        audioDeviceSelector.selectDevice(speakerphone);
        audioDeviceSelector.activate();
        Log.d(TAG, "Selected and activated " + speakerphone.getName());
}
```


**Stacktrace**
08-03 13:35:50.979 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.979 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.979 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.980 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.980 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.980 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.980 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.980 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.981 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.981 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.981 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.981 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.982 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.982 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.982 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.983 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.983 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.983 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.983 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.984 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.984 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.984 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.984 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.985 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.985 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.985 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.985 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.985 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.986 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.986 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.986 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.986 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.987 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.987 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.987 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.987 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.988 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.988 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.988 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.988 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.988 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.989 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available
08-03 13:35:50.989 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Earpiece available
08-03 13:35:50.989 15444-15444/com.twilio.video.quickstart D/AudioDeviceManager: Speakerphone available

**Comment by Alton09** [comment] 2020-08-03 17:26
Hi @aparajita-sinha . Please use the latest version `0.2.1`, which fixes this issue. I have confirmed that this issues exists on the older version that you are using `0.1.3`.

**Comment by aparajita-sinha** [comment] 2020-08-04 10:46
Hi @Alton09, yes after upgrading to version `0.2.1` the above issue has been fixed.
But still, I see that using my above code, after disconnecting Bluetooth or wired headset it goes back to earpiece instead of the speakerphone.

Let me know if I need to change my code. 

```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        audioDeviceSelector = new AudioDeviceSelector(getApplicationContext());
        savedVolumeControlStream = getVolumeControlStream();
        setVolumeControlStream(AudioManager.STREAM_VOICE_CALL);

        audioDeviceSelector.start((audioDevices, audioDevice) -> {
            Toast.makeText(this,audioDevice.getName(),Toast.LENGTH_SHORT).show();
            return Unit.INSTANCE;
        });

        List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
        Speakerphone speakerphone = null;
        for (AudioDevice audioDevice : availableAudioDevices) {
            Log.d(TAG, "Available Audio devices - " + audioDevice.getName());
            if(audioDevice instanceof Speakerphone) speakerphone = (Speakerphone) audioDevice;
        }
        audioDeviceSelector.selectDevice(speakerphone);
        audioDeviceSelector.activate();
        Log.d(TAG, "Selected and activated " + speakerphone.getName());
}
```

**Comment by aparajita-sinha** [comment] 2020-08-07 14:19
Hi @Alton09 ,Can please share an update on this?

**Comment by Alton09** [comment] 2020-08-07 15:19
Hi @aparajita-sinha . This is expected behavior in the library at the moment. The order of precedence is Bluetooth Headset -> Wired Headset -> Earpiece -> Speakerphone. We created a story for a future sprint to allow developers to change this order to whatever suits their needs. I'll update this issue as soon as I cut the PR for this enhancement. Thanks!

**Comment by Alton09** [comment] 2020-08-07 16:01
Also, as a workaround in the meantime to always select the Speakerphone, you can always select the Speakerphone in the `AudioDeviceChangeListener` callback as demonstrated below:
```
        audioDeviceSelector.start((audioDevices, audioDevice) -> {
            if(audioDevice instanceof AudioDevice.Speakerphone) {
                audioDeviceSelector.selectDevice(audioDevice);
            }
            return Unit.INSTANCE;
        });
```

**Comment by aparajita-sinha** [comment] 2020-08-10 10:43
Hi @Alton09, in version `0.2.1`, Bluetooth is not getting detected in my app when I apply the above code. It is only detecting the wired headset and speakerphone.
Will you release any other bugfix release by today?

**Comment by aaalaniz** [comment] 2020-08-10 17:25
Hey @aparajita-sinha 

We are currently prioritizing AudioSwitch bugs before adding more features. Implementing an audio device preference order (eg. Speakerphone over Earpiece) and fallback policy is considered a feature request. If you would like to fallback to speakerphone after a bluetooth device is disconnected then I suggest the following approach.

```
        audioDeviceSelector.start { audioDevices, audioDevice ->
            if (audioDevice is AudioDevice.Earpiece) {
                val speakerPhone = audioDevices.find { it is AudioDevice.Speakerphone }
                audioDeviceSelector.selectDevice(speakerPhone)
            }
        }
```

Basically if the library falls back to earpiece just revert back to speakerphone manually. This is a workaround for now, but once we prioritize this feature you should be able to specify your own order preference for selected devices.

**Comment by aparajita-sinha** [comment] 2020-08-11 07:47
Hi @aaalaniz and @Alton09 , I added this code in the `AudioDeviceChangeListener`. Now it selects the speakerphone whenever earpiece is detected. This is finally sorted.
The problem now remains that is when there is a transition to Bluetooth or wired headset it does not switch automatically. I need to manually select the desired audio option from the menu.
Let me know if I am doing anything wrong here. 

```
audioDeviceSelector.start((audioDevices, audioDevice) -> {
            if(audioDevice instanceof Earpiece){
                List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
                int selectedDeviceIndex = availableAudioDevices.indexOf(new Speakerphone());
                audioDeviceSelector.selectDevice(availableAudioDevices.get(selectedDeviceIndex));
            }
            return Unit.INSTANCE;
        });
```

Even if I set the instances of Bluetooth or Wired Headset it does not work.

```
audioDeviceSelector.start((audioDevices, audioDevice) -> {
            if (audioDevice instanceof Earpiece) {
                List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
                int selectedDeviceIndex = availableAudioDevices.indexOf(new Speakerphone());
                audioDeviceSelector.selectDevice(availableAudioDevices.get(selectedDeviceIndex));
            } else if (audioDevice instanceof WiredHeadset) {
                List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
                int selectedDeviceIndex = availableAudioDevices.indexOf(new WiredHeadset());
                audioDeviceSelector.selectDevice(availableAudioDevices.get(selectedDeviceIndex));
            } else if (audioDevice instanceof BluetoothHeadset) {
                List<AudioDevice> availableAudioDevices = audioDeviceSelector.getAvailableAudioDevices();
                int selectedDeviceIndex = availableAudioDevices.indexOf(new BluetoothHeadset(""));
                audioDeviceSelector.selectDevice(availableAudioDevices.get(selectedDeviceIndex));
            }
            return Unit.INSTANCE;
        });
```

**Comment by aaalaniz** [comment] 2020-08-11 15:01
Hey @aparajita-sinha 

Ironically this behavior is expected with the previous workaround I provided. If a developer calls `selectDevice` then they will be opted out of the "automatic" device switching provided by AudioSwitch that occurs when for example a bluetooth device is connected. We assume that because a developer called `selectDevice` that the user would like to use that specific device (eg. speakerphone) even if a bluetooth device is connected.

The good news is that you should be able to implement your own "automatic" switching with the AudioDeviceChangeListener, but it will require some book keeping in your app. Here is a snippet that might be helpful:

```
        javaAudioDeviceSelector.start(
                (audioDevices, audioDevice) -> {
                    Optional<? extends AudioDevice> bluetoothDevice = audioDevices
                            .stream()
                            .filter(it -> it instanceof AudioDevice.BluetoothHeadset)
                            .findFirst();
                    Optional<? extends AudioDevice> wiredDevice = audioDevices
                            .stream()
                            .filter(it -> it instanceof AudioDevice.WiredHeadset)
                            .findFirst();
                    Optional<? extends AudioDevice> speakerPhone = audioDevices
                            .stream()
                            .filter(it -> it instanceof AudioDevice.Speakerphone)
                            .findFirst();

                    if (bluetoothDevice.isPresent() && !(audioDevice instanceof AudioDevice.BluetoothHeadset)) {
                        javaAudioDeviceSelector.selectDevice(bluetoothDevice.get());
                    } else if (wiredDevice.isPresent() && !(audioDevice instanceof AudioDevice.WiredHeadset)) {
                        javaAudioDeviceSelector.selectDevice(wiredDevice.get());
                    } else if (speakerPhone.isPresent() && !(audioDevice instanceof AudioDevice.Speakerphone)){
                        javaAudioDeviceSelector.selectDevice(speakerPhone.get());
                    }
                    
                    AudioDevice selectedAudioDevice = javaAudioDeviceSelector.getSelectedAudioDevice() == null ?
                            audioDevice :
                            javaAudioDeviceSelector.getSelectedAudioDevice();

                    Log.d("AudioSwitch", "Selected Audio Device: " + selectedAudioDevice.getName());

                    return Unit.INSTANCE;
                });
```

**Comment by aparajita-sinha** [comment] 2020-08-12 13:40
Thanks @aaalaniz . 
Can you please share the java code snippet for the above?

**Comment by Alton09** [comment] 2020-08-12 15:11
Hi @aparajita-sinha . The snippet does appear to be in Java. Please let us know if you have any additional questions. Thanks!

**Comment by aparajita-sinha** [comment] 2020-08-12 16:06
Hi @Alton09 , my apology that I missed it. 
Thanks for your help. I will apply this fix and let you know here.

**Comment by elagarrigue** [comment] 2020-08-18 21:20
@Alton09  @aaalaniz, in our use case we need to set `Speakerphone` as default instead of `Earpiece` when no wire headset or bluetooth headset is connected. 

The rigidity is here https://github.com/twilio/audioswitch/blob/master/audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt#L253

```
 bluetoothHeadsetManager?.getHeadset(bluetoothHeadsetName)?.let {
            mutableAudioDevices.add(it)
        }
        if (wiredHeadsetAvailable) {
            mutableAudioDevices.add(WiredHeadset())
        }
        if (audioDeviceManager.hasEarpiece() && !wiredHeadsetAvailable) {
            mutableAudioDevices.add(Earpiece())
        }
        if (audioDeviceManager.hasSpeakerphone()) {
            mutableAudioDevices.add(Speakerphone())
        }
```
The earpiece is added to the list before speakerphone, and then the default device is the first one
```
 val firstAudioDevice = mutableAudioDevices[0]
```

I think the order makes sense for voip calls, but for video calls is desirable to use speaker first. If at least we have a way to set that order, that would be great.

**Comment by Alton09** [comment] 2020-08-18 21:27
Hi @elagarrigue . Thanks for the comment! We are planning to provide a way for developers to specify the order in which they would like the library to automatically select devices. In the meantime, please take a look at @aaalaniz 's [comment above](https://github.com/twilio/audioswitch/issues/45#issuecomment-671999638) for a workaround.

**Comment by elagarrigue** [comment] 2020-08-18 21:45
Thanks @Alton09 . In my use case I still need to be able to select earpiece, so I'm doing a similar workaround. Looking forward for the update :)

**Comment by Monika-Paliwal** [comment] 2020-09-21 15:02
Hi @aparajita-sinha
I am using the below-mentioned code but I am not getting the Bluetooth headset in the audio devices list. it's sometimes showing only earpiece or speaker. please let me know, why it's not working. 
I also called the audioSwitch.activate() and audioSwitch.Deactivate().
I am using a Samsung device.
AudioSwitch audioSwitch = new AudioSwitch(getApplicationContext());
        audioSwitch.start((audioDevices, audioDevice) -> {
            List<AudioDevice> availableAudioDevices = audioSwitch.getAvailableAudioDevices();
            int selectedDeviceIndex = availableAudioDevices.indexOf(new AudioDevice.BluetoothHeadset(""));
            if (selectedDeviceIndex < -1) {
                audioSwitch.selectDevice(availableAudioDevices.get(selectedDeviceIndex));
            }
            return Unit.INSTANCE;
        });

**Comment by Alton09** [comment] 2020-09-22 16:14
Hi @Monika-Paliwal . Try the following Java snippet instead:
```
AudioSwitch audioSwitch = new AudioSwitch(getApplicationContext());
audioSwitch.start((audioDevices, audioDevice) -> {
    for(AudioDevice device: audioDevices) {
        if(device instanceof AudioDevice.BluetoothHeadset) {
            audioSwitch.selectDevice(device);
        }
    }
    return Unit.INSTANCE;
});
```
**Note** that this will always select the bluetooth headset if it is available.

**Comment by yatw** [comment] 2020-09-22 22:37
Hello, for audioDevices list in
```
     audioSwitch.start((audioDevices, audioDevice) -> {
           
     });
```
Is it normal that a phone automatically have a earpiece without anything plugin?

When I plug in a ear bug, the audioDevices becomes a 2 item list of Wired Device and Speakerphone, so earpiece is replaced by the ear bug. When I unplug the ear bug, it becomes a 2 item list of Earpiece and Speakerphone.

What is this earpiece device? Is it like a phone call there is talking mode and speaker mode. Speaker mode is the louder version and talking mode is the softer version (earpiece)?

**Comment by Alton09** [comment] 2020-09-22 22:51
Hi @yatw . What you are describing is the expected behavior for the library. A phone generally has two audio devices by default, the earpiece (speaker at the top of the phone used when holding the device to your ear) and the speakerphone which is the louder speaker that is used when the phone is held away from your ear. The library either shows the wired headset or earpiece but not both at the same time, since if a headset is plugged in, the intention of the user is to use the headset and not the earpiece.

**Comment by Monika-Paliwal** [comment] 2020-09-23 13:27
> Hi @Monika-Paliwal . Try the following Java snippet instead:
> 
> ```
> AudioSwitch audioSwitch = new AudioSwitch(getApplicationContext());
> audioSwitch.start((audioDevices, audioDevice) -> {
>     for(AudioDevice device: audioDevices) {
>         if(device instanceof AudioDevice.BluetoothHeadset) {
>             audioSwitch.selectDevice(device);
>         }
>     }
>     return Unit.INSTANCE;
> });
> ```
> 
> **Note** that this will always select the bluetooth headset if it is available.



> Hi @Monika-Paliwal . Try the following Java snippet instead:
> 
> ```
> AudioSwitch audioSwitch = new AudioSwitch(getApplicationContext());
> audioSwitch.start((audioDevices, audioDevice) -> {
>     for(AudioDevice device: audioDevices) {
>         if(device instanceof AudioDevice.BluetoothHeadset) {
>             audioSwitch.selectDevice(device);
>         }
>     }
>     return Unit.INSTANCE;
> });
> ```
> 
> **Note** that this will always select the bluetooth headset if it is available.

Hey @Alton09 
I added the code above-mentioned code but it's not working in second call because the Bluetooth headset is already connected So that time bluetooth headset option is not showing in the audioDevices list it always shows earpiece and speakerphone in the list.

**Comment by Alton09** [comment] 2020-10-08 22:20
@aparajita-sinha @elagarrigue This feature is now supported in the latest release [1.1.0](https://github.com/twilio/audioswitch/releases/tag/1.1.0)! Closing this issue for now. Please feel free to reach out if there are any additional questions. Thanks!

**Closed by Alton09** 2020-10-08 22:20 UTC
Labels: enhancement

**Comment by aparajita-sinha** [comment] 2020-10-09 08:43
Hi @Alton09,
Thanks for the update.
Can you please help how to use the feature to set the audio device preference? I would require the code using java.
My app requires to switch between audio devices Bluetooth, wired headset, and loudspeaker.

**Comment by Alton09** [comment] 2020-10-09 15:19
@aparajita-sinha Of course! This code snippet should meet your requirements:
```java
List<Class<? extends AudioDevice>> preferredDevices = new ArrayList<>();
preferredDevices.add(BluetoothHeadset.class);
preferredDevices.add(WiredHeadset.class);
preferredDevices.add(Speakerphone.class);
AudioSwitch audioSwitch = new AudioSwitch(context, false, focusChange -> {}, preferredDevices);
```
