### ISSUE TITLE
BluetoothHeadsetConnectionListener in BluetoothHeadsetManager causes inconsistency in the bluetooth device detection

### ISSUE THREAD

**Issue by filipebatista** [twilio/audioswitch#131] opened 2022-10-26 10:58 UTC
**Describe the bug**
The `BluetoothHeadsetManager` receives an update form the system indicating `STATE_AUDIO_CONNECTED` is calling the `BluetoothHeadsetConnectionListener.onBluetoothHeadsetStateChanged()` with **no** Bluetooth device name. This will trigger the `BluetoothHeadsetConnectionListener` registered in `AudioSwitch` that consequently will remove the previous Bluetooth device detected by AudioSwitch. 

**To Reproduce**
1. Pair the bluetooth audio device. Check that the `STATE_CONNECTED` is received in `BluetoothHeadsetManager` and that the device becomes available in`AudioSwitch.availableAudioDevices`.
2. Wait a few moments to receive the `STATE_AUDIO_CONNECTED`  in `BluetoothHeadsetManager` and that the previously detected device is removed from `AudioSwitch.availableAudioDevices`.

**Expected behavior**
In `BluetoothHeadsetManager` when receiving a`STATE_AUDIO_CONNECTED` should call the `headsetListener?.onBluetoothHeadsetStateChanged(bluetoothDevice.name)`

**AudioSwitch Version**
Version: 1.1.5

**Comment by filipebatista** [comment] 2023-02-02 09:35
I was able to reproduce the issue several times, with a Xiaomi mi lite 11, Samsung A10 and with airpods and defunc true go .
Only when I performed the change of the open pull request the device name appeared correctly in the. Audioswitch available devices.

**Comment by afalls-twilio** [comment] 2023-11-13 16:13
@filipebatista are you able to reproduced this with the quickstart? we are struggling to reproduce this issue and looking for a way to so that we can fix it.

**Comment by filipebatista** [comment] 2023-11-15 13:17
Hello 👋
Didn't try to replicate with the quick start,  nevertheless currently I'm no longer with the product that used your SDK so I can't really try it. 
Feel free to close if you find relevant.
Thanks

**Comment by afalls-twilio** [comment] 2024-01-08 16:07
closing due to no longer customer issue

**Closed by afalls-twilio** 2024-01-08 16:07 UTC
Labels: bug
