### ISSUE TITLE
USB Headset audio always defaults or switches 5-10 seconds after requesting focus

### ISSUE THREAD

**Issue by schuranator** [twilio/audioswitch#150] opened 2023-05-24 00:24 UTC
I'm noticing issues with the Samsung S7+ Android 12 and 13 along with the Pixel 7 Android 13.

I created a small Activity that would allow me to toggle which audio output to use. The toggle works initially but after 5-10 seconds I see the audio get switched back to the USB Headset Audio output.

Here is some logs:
2023-05-23 13:42:52.399  1061-1857  SoundAlive...384 arch64 audioserver                          I  SoundAlive_SRC384: Instance 173 Init(outFs 8, InFs 5, chnum 1, outBW 3, inBW 3)
2023-05-23 13:42:52.399  1061-1857  Samsung_So...SRC arch64 audioserver                          I  SRC384 version Samsung SoundAlive SRC ver320 arch64  2021.08.04 (Cppref for ARM64, ver.300.c 32bit 07_10_2016 based)
2023-05-23 13:42:52.594  1061-1857  SoundAlive...384 arch64 audioserver                          I  ~SoundAlive_SRC384(): instance 173

![cc600357-d91f-4171-8a37-b47ca6cd2b42](https://github.com/twilio/audioswitch/assets/2049097/030f30c6-108d-488d-b87b-7dcf3c258a00)

**Comment by angeloraso** [comment] 2023-05-24 11:51
Hi!
- I am not sure if it will be the same problem but I have noticed that in Android 12+ I have to reconfirm the mode change after modifying the audio output device
- Otherwise, after 5s Android change back to default audio output device

**Example code:**
```
audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
             AudioDeviceInfo speakerphoneDevice = getAudioDevice(AudioDeviceInfo.TYPE_BUILTIN_SPEAKER);
             if (speakerphoneDevice != null) {
                 success = audioManager.setCommunicationDevice(speakerphoneDevice);
                 if (success) {
                     audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
                 } else {
                     Log.d(TAG, "Speaker error");
                 }
             }
```

I hope it helps you

**Comment by schuranator** [comment] 2023-05-24 16:38
I tried this workflow but still have the cut out after a few seconds of playing. I have a better log not sure if this helps.
[AudioSwitchLog.txt](https://github.com/twilio/audioswitch/files/11556934/AudioSwitchLog.txt)

**Comment by acalpitojr** [comment] 2023-06-24 06:23
I am experiencing the same issue.  After switching to MODE_IN_COMMUNICATION, after about 5 seconds, the mode auto switches to MODE_NORMAL. 

I tried @angeloraso example code and I still see the problem.

**Comment by ocarevs** [comment] 2023-07-26 10:43
@schuranator I've been unable to reproduce the issue so far. Can you add a log file with `AudioSwitch.loggingEnabled = true` set where you encounter this issue?

**Comment by afalls-twilio** [comment] 2023-10-30 15:06
Closing due to a lack of customer response.

**Closed by afalls-twilio** 2023-10-30 15:06 UTC
Labels: bug
