### ISSUE TITLE
Audio and video preview is not working on AndroidX

### ISSUE THREAD

**Issue by amirocpc** [twilio/audioswitch#17] opened 2020-05-14 04:04 UTC
**Description**
We are using Twilio Android programmable sample which works fine but in AndroidX based on the error logs it seems like **audioDeviceSelector.activate();** is crashing and therefore after participants join a room they don't see or hear each other. 

Below is the sample code were AndroidX is used:
https://github.com/mukeshocpc/TwillioSample

**Device Info**
Galaxy Note8
Model #: SM-N950U
Android Version: 7.1.1

minSdkVersion 21
targetSdkVersion 29
versionCode 1
versionName "1.0"

'videoAndroid'       : '5.6.0',
'audioSwitch'        : '0.1.0'

**Comment by Alton09** [comment] 2020-05-14 17:41
Hi @amirocpc. Thank you for reaching out! Can you please share the exception stack trace so we can help troubleshoot? Also, please be sure to follow the [Getting Started](https://github.com/twilio/audioswitch#getting-started) instructions before using the AudioSwitch library, as there is some setup required before calling `audioDeviceSelector.activate()`.

**Comment by mukeshocpc** [comment] 2020-05-14 18:28
error stack-trace :
2020-05-11 11:27:53.845 26942-26974/indiqube.com.twilliotest E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
Process: indiqube.com.twilliotest, PID: 26942
java.lang.IllegalStateException
at com.twilio.audioswitch.selection.AudioDeviceSelector.activate(AudioDeviceSelector.kt:183)
at indiqube.com.twilliotest.VideoActivity.connectToRoom(VideoActivity.kt:773)
at indiqube.com.twilliotest.VideoActivity.access$connectToRoom(VideoActivity.kt:36)
at indiqube.com.twilliotest.VideoActivity$retrieveAccessTokenfromServer$1.onResponse(VideoActivity.kt:751)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)

i tried to remove the audio switch library
 but when we join the room there is no audio on some devices
and there is an issue in Video Preview a user can see its own image 
it should see other preview user who joined the room

the code is same as twill0 starter kotlin app it will great if u can see the repo i shared

https://github.com/mukeshocpc/TwillioSample

**Comment by Alton09** [comment] 2020-05-15 16:23
Hi @mukeshocpc . The reason why you are seeing that exception is because you are not selecting an audio device before calling `audioDeviceSelector.activate()`. Please take a look at the `showAudioDevices()` in `VideoActivity.kt` in your example repository. It demonstrates how to select a device from an available list of audio devices. For a thorough example on viewing local and remote participant video in a video room, checkout the [Twilio Video App](https://github.com/twilio/twilio-video-app-android).

I'm closing this issue for now as it is not a bug in the library. Please reach out if you need any additional help getting your example to work. Thanks!

**Closed by Alton09** 2020-05-15 16:23 UTC
Labels: question

**Comment by amirocpc** [comment] 2020-05-18 22:10
@Alton09 As mentioned in this issue, in AndroidX (https://github.com/mukeshocpc/TwillioSample) when two people are in a room, THEY DON'T SEE EACH OTHER which is not related to audioDeviceSelector.activate(). The video issue is not mentioned in your response here and ticket is closed by your colleagues in other related repositories.

**Comment by aaalaniz** [comment] 2020-05-21 15:45
Hey @amirocpc 

It seems that there was a little bit of confusion between the issue filed by @mukeshocpc and yourself. There was initially a problem with a runtime exception being thrown as a result of not activating an audio device. It appears that issue now resolved with @Alton09 's guidance.

However, it seems like there is a separate issue related to not seeing or hearing participant's. Please open an issue on the [video android quickstart](https://github.com/twilio/video-quickstart-android) and fill out the issue template properly so we can provide guidance.

Thanks!

**Comment by amirocpc** [comment] 2020-05-24 20:28
@aaalaniz thanks, issue created [here](https://github.com/twilio/video-quickstart-android/issues/518)

**Comment by jonathanpv** [comment] 2020-08-08 03:19
This happened to me on my Galaxy S20 but not on my Samsung Sol, I migrated the video-quickstart-android (quickstartKotlin) app to androidx using the intellij refactor feature. I found commenting out the line audioDeviceSelector.activate() found in the connectToRoom() function inside VideoActivity.kt from the quickstart app and it ran fine. Putting this in case someone just wants to run it quickly. I'll look into the docs now haha

**Comment by chandrikaReddyBunga** [comment] 2020-11-03 04:54
java.lang.IllegalStateException
        at com.twilio.audioswitch.AudioSwitch.activate(AudioSwitch.kt:233)
        at com.vedas.spectrocare.PatientVideoCallModule.VideoActivity.connectToRoom(VideoActivity.java:442)
getting error on connectRoom method android .
