### ISSUE TITLE
AudioSwitch selected bluetooth headset but sound is still from phone speaker

### ISSUE THREAD

**Issue by brian-chung-dragon** [twilio/audioswitch#66] opened 2020-08-25 04:35 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/audioswitch/issues)
>  * [Changelog](https://github.com/twilio/audioswitch/blob/master/CHANGELOG.md)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

**Describe the bug**
I implemented a logic to change the audio channel automatically once the audio device is connected to the phone.
e.g.
Earpiece -> Connect to a Bluetooth headset -> Audio switch will select BluetoothHeadset automatically
Disconnect from Bluetooth headset -> Audio switch will switch the channel back to Earpiece

and there is an issue that audio switch library selected BluetoothHeadset, but the sound still come from phone speaker.

This issue only happens sometimes, but I can reproduce it with the steps below.
[audioSwitchLog.txt](https://github.com/twilio/audioswitch/files/5121342/audioSwitchLog.txt)

**To Reproduce**
1. Make call without connecting to Bluetooth earphone.
2. Hear voice from phone speaker
3. Connect to Bluetooth earphone after 2-3 secs (connected to my Airpods)
4. Audio switch can detect Airpods and able to select it
5. No sound from Airpods, and can still hear the sound from phone speaker

**Expected behavior**
Expected the sound should play on my Airpods

**Actual behavior**
Sound still play on phone speaker

**Screenshots**
I don't have screenshot, but I have a sample code to reproduce the issue.

**Android Device (please complete the following information):**
 - Device: Huawei P30 Pro
 - API Version: 26

**Version**
- Version: 9

**Comment by aaalaniz** [comment] 2020-08-25 14:54
Hey @brian-chung-dragon 

What version of AudioSwitch are you using?

Thank you for filing the issue!

**Comment by brian-chung-dragon** [comment] 2020-08-26 05:51
@aaalaniz I am using AudioSwitch v1.0

**Comment by Alton09** [comment] 2020-08-26 15:36
Hi @brian-chung-dragon. Thanks for providing all of the info about this bug. Can you please also share some code snippets of how you are interacting with AudioSwitch?

**Comment by brian-chung-dragon** [comment] 2020-08-27 01:35
I changed the voice quick start sample code a bit to reproduce the issue. And listed out all my findings into the README.txt
[sample.zip](https://github.com/twilio/audioswitch/files/5133462/sample.zip)

**Comment by koudai-kikuchi-coconala** [comment] 2020-08-28 02:31
Having an exactly same problem.

**To Reproduce:** 
exactly same as @brian-chung-dragon 

**Library:** 
- AudioSwitch v1.0.0

**Android Device:**
 - pixel 4 (Android 10)

**Bluetooth Devices:** 
- WH-1000XM3 (SONY)
- WF-1000XM3 (SONY)
- AS800(AfterShokz)

**Code:** 
Basically same as sample, but slightly changed listener for automatically connect

```kotlin
audioDeviceSelector.start { _, device ->
    // force connecting to speakerphone if earpiece is detected
    val audio = if (device == null || device is AudioDevice.Earpiece) {
          audioDeviceSelector.availableAudioDevices.find {
              it is AudioDevice.Speakerphone
          }
     } else {
        device
     }
     audioDeviceSelector.selectDevice(audio)
}
```

**NOTES:**
If process is stopped for 1~3 sec with debugger at `audioDeviceSelector.selectDevice(audio)` and continue process, switching to bluetooth device works perfectly.  It seems like whenever listener detect a device, a device is somehow not ready to be connected with `selectDevice` call.

**Comment by brian-chung-dragon** [comment] 2020-08-31 03:17
hi @Alton09 , are you able to reproduce the issue? Do I need to provide more information? Thanks.

**Comment by Alton09** [comment] 2020-09-01 16:31
Hi @brian-chung-dragon . Sorry for the delay. I am investigating this issue and will report my findings soon. Thanks!

**Comment by Alton09** [comment] 2020-09-01 23:28
@brian-chung-dragon Can you please give this version, `1.0.1-SNAPSHOT`, a try? We believe the issue may be fixed in this release. Note that this is not an official release, we want to verify if this resolves the issue first before cutting an official release. Thanks!

**Comment by brian-chung-dragon** [comment] 2020-09-02 02:12
Thanks @Alton09 , will get back to you on Friday or next week Monday.

**Comment by brian-chung-dragon** [comment] 2020-09-04 02:53
Hi @Alton09 , after I updated the config in gradle to use 1.0.1-SNAPSHOT. And the project couldn't find the Kotlin module.
Do you know how to solve this? (Sorry I am new to Android)

![image](https://user-images.githubusercontent.com/52231108/92194270-d9867d00-ee9c-11ea-842b-a28e1e9bc3e0.png)

**Comment by Alton09** [comment] 2020-09-04 17:18
@brian-chung-dragon Ah yeah that's because the voice quickstart doesn't use Kotlin. Try adding the following dependency to the app/build.gradle file: `implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0"`

**Comment by brian-chung-dragon** [comment] 2020-09-07 03:23
Hi @Alton09 , I can still reproduce the problem using `1.0.1-SNAPSHOT`

**Comment by Alton09** [comment] 2020-09-08 17:08
Hi @brian-chung-dragon . Thank you for verifying. Our QA team was able to reproduce this issue on Huawei P10 and P20 devices. We will continue to investigate this issue and update on you on our findings. Thanks!

**Comment by Alton09** [comment] 2020-09-14 23:22
@brian-chung-dragon We have found that this issue occurs less frequently with the latest version of the library, [1.0.1](https://github.com/twilio/audioswitch/releases/tag/1.0.1), please give it a try and let us know if it helps. We are still investigating this issue in the meantime. Thanks!

**Comment by brian-chung-dragon** [comment] 2020-09-15 07:08
Thanks @Alton09 will have a try this week, do you know is this issue happens more frequently on Huawei devices only?

**Comment by Alton09** [comment] 2020-09-15 16:25
@brian-chung-dragon Out of the devices that we have tested the library on, this issue only occurs on Huawei devices.

**Comment by brian-chung-dragon** [comment] 2020-09-16 03:58
Thanks @Alton09 , I just did a quick test on release 1.0.1. The bluetooth issue seems improved but like what you said, the issue is still occurs in Huawei devices.

**Comment by Alton09** [comment] 2020-09-17 22:32
Hi @brian-chung-dragon . We have spent quite a bit of time on this issue and decided to close it and label it as `won't fix`. After running various test scenarios on a Huawei P30, 1.0.1 has proven to consistently connect audio on a bluetooth headset while on a call. We ran these tests on the [Twilio Video App](https://github.com/twilio/twilio-video-app-android). Thanks for reaching out and please feel free to open any other issues related to this library if needed. Thanks!

**Closed by Alton09** 2020-09-17 22:32 UTC
Labels: bug

**Comment by Monika-Paliwal** [comment] 2020-09-21 14:50
Hey @Alton09 @brian-chung-dragon 
I am using below mentioned code but i am not getting the buletooth headset in the audio devices list. it's sometime showing only earpiece or speaker. please let me know , why it's not working 
audioSwitch = new AudioSwitch(getApplicationContext());
        audioSwitch.start((audioDevices, audioDevice) -> {
            List<AudioDevice> availableAudioDevices = audioSwitch.getAvailableAudioDevices();
            int selectedDeviceIndex = availableAudioDevices.indexOf(new AudioDevice.BluetoothHeadset(""));
            if (selectedDeviceIndex < -1) {
                audioSwitch.selectDevice(availableAudioDevices.get(selectedDeviceIndex));
            }
            return Unit.INSTANCE;
        });

**Comment by ataballyyeva** [comment] 2024-04-25 16:00
I have that issue too with latest version @Monika-Paliwal
